- name: reload circus
  shell: "{{ circusctl }} {{ item }}"
  with_items:
      - reloadconfig
      - restart smart_classroom
      - restart smart_classroom_mqtt

- name: restart nginx
  service:
    name: nginx
    state: restarted
