---
# Debian specific tasks

- name: add nodesource apt key
  apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present
  when: ansible_distribution == 'Ubuntu'

- name: add nodejs repos
  apt_repository:
      filename: nodesource
      repo: deb https://deb.nodesource.com/node_9.x {{ ansible_distribution_release }} main
      update_cache: yes
      state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install required debian jessie packages
  apt: name={{ item }} state=latest default_release=jessie-backports
  with_items:
      - python3
      - python3-setuptools
      - python3-pip
      - python3-dev
      - python
      - python-setuptools
      - python-pip
      - python-dev
      - nodejs-dev=0.10.*
      - nodejs=0.10.*
      - nodejs-legacy=0.10.*
      - npm
  when: ansible_distribution_release == "jessie"

- name: Install required debian packages
  apt: name={{ item }} state=latest
  with_items:
      - python3
      - python3-setuptools
      - python3-pip
      - python3-dev
      - python
      - python-setuptools
      - python-pip
      - python-dev
      - nodejs
      - npm
  when: ansible_distribution_release != "jessie" and ansible_distribution != 'Ubuntu'

- name: Install required Ubuntu packages
  apt: name={{ item }} state=latest
  with_items:
      - python3
      - python3-setuptools
      - python3-pip
      - python3-dev
      - python
      - python-setuptools
      - python-pip
      - python-dev
      - nodejs
  when: ansible_distribution == 'Ubuntu'
