---
# Debian specific tasks

- name: Install required debian packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - mariadb-client
      - mariadb-server
      - phpmyadmin
