---
# Tasks to install the ISC dhcp server
#
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific taks
  include: "{{ ansible_os_family }}.yml"

- name: Ansible service manager
  debug: var=ansible_service_mgr

- name: "Copy dhcpd config"
  template:
      src: "dhcpd.conf.j2"
      dest: "/etc/dhcp/dhcpd.conf"
      owner: root
      group: root
      mode: 644

- name: "Copy static leases config"
  template:
      src: "static_leases.conf.j2"
      dest: "/etc/dhcp/static_leases.conf"
      owner: root
      group: root
      mode: 644

- name: allow dhcpd in iptables public input
  iptables: 
      chain: "{{ iptables_input_chain }}"
      protocol: udp
      destination_port: "67:68"
      in_interface: "{{ dhcp_interface }}"
      source: "{{ dhcp_network }}"
      jump: ACCEPT
      state: present
  when: (firewalld_enabled is not defined or not firewalld_enabled or firewalld_enabled=="false") and (ufw_enabled is not defined or not ufw_enabled or ufw_enabled=="false")

- name: allow dhcpd in firewalld
  firewalld:
      service: dhcp
      source: "{{ dhcp_network }}"
      permanent: true
      immediate: true
      state: enabled
  when: firewalld_enabled is defined and (firewalld_enabled==true or firewalld_enabled=="true")

- name: allow 80/443 in ufw
  ufw:
      rule: "allow"
      port: dhcp
      proto: udp
      interface: "{{ dhcp_interface }}"
      state: enabled
  when: ufw_enabled is defined and (ufw_enabled==true or ufw_enabled=="true")

- name: "Enable dhcpd service"
  service:
      name: dhcpd
      state: restarted
      enabled: yes
