---
# Debian specific tasks

- name: Install Debian Requirements
  apt: name={{ item }} state=latest 
  with_items:
      - libsasl2-dev
      - redis-server
      - libssl-dev
      - libffi-dev
      - libldap2-dev

