---

- name: Enable Jessie-Backports
  apt_repository:
      repo: deb http://httpredir.debian.org/debian jessie-backports main
      state: present
  when: ansible_distribution_release == "jessie"

- name: Install Debian updates (aptitude safe upgrade)
  apt: upgrade=safe update_cache=yes

- name: Install basic debian packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - debian-keyring
      - unzip
      - git
      - ntp
      - vim
      - screen
      - htop
      - cron
      - curl
      - pwgen

- name: Set debian locale
  debconf:
      name: locales
      question: locales/default_environment_locale
      value: en_US.UTF-8
      vtype: select

- name: /etc/locale.gen
  lineinfile:
    dest: /etc/locale.gen
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  register: locale_changed
  with_items:
    - { regexp: '^#? ?en_US.UTF-8 UTF-8', line: 'en_US.UTF-8 UTF-8', state: present }
    - { regexp: '^#? ?en_PH.UTF-8 UTF-8', line: 'en_PH.UTF-8 UTF-8', state: present }

- name: rebuild locales database
  command: "{{ item }}"
  when: locale_changed.changed
  with_items:
    - /usr/sbin/locale-gen
    - dpkg-reconfigure locales -f noninteractive
