---

- name: Setup apt cache proxy
  lineinfile:
      dest: /etc/apt/apt.conf.d/02proxy
      regexp: 'Acquire::http::Proxy.*'
      line: 'Acquire::http::Proxy "{{ apt_cache_url }}";'
      state: present
      create: yes
  when: apt_cache_url is defined

- name: Setup apt cache proxy direct hosts
  lineinfile:
      dest: /etc/apt/apt.conf.d/02proxy
      line: 'Acquire::http::Proxy::{{ item }} DIRECT;'
      state: present
      create: yes
  with_items: "{{ apt_cache_direct_urls }}"
  when: apt_cache_direct_urls is defined


- name: Enable Jessie-Backports
  apt_repository:
      repo: deb http://httpredir.debian.org/debian jessie-backports main
      state: present
  when: ansible_distribution_release == "jessie"

- name: Install Debian updates (aptitude safe upgrade)
  apt: upgrade=safe update_cache=yes

- name: Install basic debian packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - [['debian-keyring', 'aptitude', 'unzip', 'git', 'ntp', 'vim', 'bzip2', 'screen', 'htop', 'cron', 'curl', 'pwgen']]

- name: Install ufw
  apt: name=ufw state=present update_cache=yes
  when: ufw_enabled is defined and ufw_enabled

- name: Set debian locale
  debconf:
      name: locales
      question: locales/default_environment_locale
      value: en_US.UTF-8
      vtype: select

- name: /etc/locale.gen
  lineinfile:
    dest: /etc/locale.gen
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  register: locale_changed
  with_items:
    - { regexp: '^#? ?en_US.UTF-8 UTF-8', line: 'en_US.UTF-8 UTF-8', state: present }
    - { regexp: '^#? ?en_PH.UTF-8 UTF-8', line: 'en_PH.UTF-8 UTF-8', state: present }

- name: rebuild locales database
  command: "{{ item }}"
  when: locale_changed.changed
  with_items:
    - /usr/sbin/locale-gen
    - dpkg-reconfigure locales -f noninteractive
