---

- name: Show groups for this host
  debug: var=group_names

- name: What distro version?
  debug: var="{{ item }}"
  with_items:
      - ansible_distribution
      - ansible_distribution_release

- name: Include OS-specific taks
  include: "{{ ansible_os_family }}.yml"

- name: ssh disable password auth
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
