---

- name: Show groups for this host
  debug: var=group_names

- name: Get user id
  shell: "id"
  register: userid

- name: What distro version?
  debug: var="{{ item }}"
  with_items:
      - ansible_distribution
      - ansible_distribution_release
      - ansible_distribution_version
      - ansible_lsb.major_release
      - ansible_distribution_major_version
      - userid.stdout

- name: Include OS-specific taks
  include: "{{ ansible_os_family }}.yml"

- name: ssh disable password auth
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present

- name: allow ssh in iptables public input
  iptables: 
      chain: "{{ iptables_input_chain }}"
      destination: 0.0.0.0/0
      ctstate: NEW
      protocol: tcp
      destination_port: "{{ item }}"
      source: 0.0.0.0/0
      jump: ACCEPT
      state: present
  with_items:
      - 22
  when: (firewalld_enabled is not defined or not firewalld_enabled) and (ufw_enabled is not defined or not ufw_enabled)

- name: allow ssh in firewalld
  firewalld:
      service: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
  with_items:
      - ssh
  when: firewalld_enabled is defined and firewalld_enabled

- name: allow ssh in ufw
  ufw:
      port: "{{ item }}"
      state: enabled
      policy: allow
  with_items:
      - ssh
  when: ufw_enabled is defined and ufw_enabled

