---

- name: setup_yum_repos
  yum_repository: name={{item.name}} description={{item.description}} baseurl={{item.url}} state={{item.state}}
  with_items:
      - name: foundationu
        description: Foundation University mirro
        url: http://mirror.itops.foundationu.com/centos/7/os/x86_64/
        state: absent
      - name: epel
        description: EPEL YUM repo
        url: http://mirror.rise.ph/fedora-epel/7/x86_64/
        gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
        state: present

- name: epel gpg keys
  yum: name=epel-release state=present

- name: install selinux software
  yum: name={{ item }} state=present
  with_items:
      - setroubleshoot-server
      - policycoreutils-python
  when: selinux_host is defined and selinux_host

- name: upgrade all packages
  yum: name=* state=latest update_cache=yes

- name: Install basic packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
      - git
      - ntp
      - vim
      - screen
      - htop
      - curl
      - pwgen
