---
# Debian specific tasks

- name: Install required debian jessie packages
  apt: name={{ item }} state=latest default_release=jessie-backports
  with_items:
      - python3
      - python3-setuptools
      - python3-pip
      - python3-dev
      - python
      - python-setuptools
      - python-pip
      - python-dev
      - postgresql-server-dev-9.4
      - postgresql-server-dev-all
      - libpq-dev
      - mysql-client
      - libmysqlclient-dev
  when: ansible_distribution_release == "jessie"

- name: Install required debian packages
  apt: name={{ item }} state=latest
  with_items:
      - python3
      - python3-setuptools
      - python3-pip
      - python3-dev
      - python
      - python-setuptools
      - python-pip
      - python-dev
      - postgresql-server-dev-all
      - mysql-client
      - libmysqlclient-dev
  when: ansible_distribution_release != "jessie"
